In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('fake_or_real_news.csv')

In [ ]:
df.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='object')

In [ ]:
df=df.drop(columns='Unnamed: 0')

In [ ]:
df.head()

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [ ]:
df['title']=df['title'].apply(lambda x: x.lower())
df['text']=df['text'].apply(lambda x: x.lower())

In [ ]:
def remove_punc(txt):
  t=''
  for i in txt:
    if i.isalpha() or i==' ':
      t+=i
  return t
df['title']=df['title'].apply(remove_punc)
df['text']=df['text'].apply(remove_punc)

In [ ]:
df.head()

,title,text,label
0,you can smell hillarys fear,daniel greenfield a shillman journalism fellow...,FAKE
1,watch the exact moment paul ryan committed pol...,google pinterest digg linkedin reddit stumbleu...,FAKE
2,kerry to go to paris in gesture of sympathy,us secretary of state john f kerry said monday...,REAL
3,bernie supporters on twitter erupt in anger ag...,kaydee king kaydeeking november the lesson ...,FAKE
4,the battle of new york why this primary matters,its primary day in new york and frontrunners h...,REAL

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize
df['title']=df['title'].apply(word_tokenize)
df['text']=df['text'].apply(word_tokenize)

In [ ]:
df.head()

,title,text,label
0,"[you, can, smell, hillarys, fear]","[daniel, greenfield, a, shillman, journalism, ...",FAKE
1,"[watch, the, exact, moment, paul, ryan, commit...","[google, pinterest, digg, linkedin, reddit, st...",FAKE
2,"[kerry, to, go, to, paris, in, gesture, of, sy...","[us, secretary, of, state, john, f, kerry, sai...",REAL
3,"[bernie, supporters, on, twitter, erupt, in, a...","[kaydee, king, kaydeeking, november, the, less...",FAKE
4,"[the, battle, of, new, york, why, this, primar...","[its, primary, day, in, new, york, and, frontr...",REAL

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from nltk.corpus import stopwords
stop_words=stopwords.words('english')

In [ ]:
def remove_stop_words(txt):
  t=[]
  for i in txt:
    if i not in stop_words:
      t.append(i)
  return ' '.join(t)
df['title']=df['title'].apply(remove_stop_words)
df['text']=df['text'].apply(remove_stop_words)

In [ ]:
df.head()

,title,text,label
0,smell hillarys fear,daniel greenfield shillman journalism fellow f...,FAKE
1,watch exact moment paul ryan committed politic...,google pinterest digg linkedin reddit stumbleu...,FAKE
2,kerry go paris gesture sympathy,us secretary state john f kerry said monday st...,REAL
3,bernie supporters twitter erupt anger dnc trie...,kaydee king kaydeeking november lesson tonight...,FAKE
4,battle new york primary matters,primary day new york frontrunners hillary clin...,REAL

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['label']=le.fit_transform(df['label'])

In [ ]:
X=df.drop(columns='label')
y=df['label']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer

In [ ]:
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train)
X_test_bow=bow.fit_transform(X_test)

In [ ]:
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.fit_transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

lg=LogisticRegression()
lg.fit(X_train_bow,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [2, 4244]